"""
auto_followup.py — Missed-Lead Detector
Sends a threaded, context-aware follow-up email to a missed lead.
Duplicate-prevention: tracks sent IDs so the same lead never gets two emails.

SMTP retries with exponential backoff: if a send fails (network error,
rate-limit, auth hiccup), the system retries up to SMTP_MAX_RETRIES times
with increasing delays (2s → 4s → 8s … capped at 60s).  Emails that
exhaust all retries are logged to logs/failed_leads.json for manual review.

-- REAL SMTP USAGE -------------------------------------------------
Set environment variables before running:
    SMTP_HOST   = smtp.gmail.com
    SMTP_PORT   = 587
    SMTP_USER   = youremail@gmail.com
    SMTP_PASS   = your_app_password   (Gmail App Password)
    SENDER_NAME = Your Company Name

Retry tuning (all optional):
    SMTP_MAX_RETRIES      = 3       (default)
    SMTP_RETRY_BASE_DELAY = 2       (seconds, doubles each retry)
    SMTP_RETRY_MAX_DELAY  = 60      (cap per-retry wait)

In demo mode the email is printed to stdout; no real SMTP required.
--------------------------------------------------------------------
"""

import os, json, re, smtplib, time
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText

SMTP_HOST   = os.getenv("SMTP_HOST",   "smtp.gmail.com")
SMTP_PORT   = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER   = os.getenv("SMTP_USER",   "")
SMTP_PASS   = os.getenv("SMTP_PASS",   "")
SENDER_NAME = os.getenv("SENDER_NAME", "Sales Team")
DEMO_MODE   = not bool(SMTP_USER)

# Retry settings for SMTP sends
SMTP_MAX_RETRIES  = int(os.getenv("SMTP_MAX_RETRIES", "3"))
SMTP_RETRY_BASE   = float(os.getenv("SMTP_RETRY_BASE_DELAY", "2"))   # seconds
SMTP_RETRY_CAP    = float(os.getenv("SMTP_RETRY_MAX_DELAY", "60"))   # seconds

SENT_LOG   = os.path.join(os.path.dirname(__file__), "..", "logs", "sent_leads.json")
FAILED_LOG = os.path.join(os.path.dirname(__file__), "..", "logs", "failed_leads.json")
os.makedirs(os.path.dirname(SENT_LOG), exist_ok=True)


# ── Persistence helpers ────────────────────────────────────────────────
# NOTE: No file locking here — acceptable because callers are sequential
# (single-threaded loops in inbox_monitor / orchestrator).  Add locking
# if these helpers are ever called from concurrent threads.

def _load_sent() -> set:
    if os.path.exists(SENT_LOG):
        with open(SENT_LOG) as f:
            return set(json.load(f))
    return set()

def _save_sent(sent: set):
    with open(SENT_LOG, "w") as f:
        json.dump(sorted(sent), f, indent=2)

def _load_failed() -> dict:
    if os.path.exists(FAILED_LOG):
        with open(FAILED_LOG) as f:
            return json.load(f)
    return {}

def _save_failed(failed: dict):
    with open(FAILED_LOG, "w") as f:
        json.dump(failed, f, indent=2, default=str)


# ── Email builder ──────────────────────────────────────────────────────

def _build_email(lead: dict) -> MIMEMultipart:
    """Build a threaded follow-up email.

    If the lead dict contains 'reply_body' and/or 'reply_subject' (generated by
    smart_reply_engine.generate_reply), those are used as the email content.
    Otherwise, falls back to a generic follow-up template.
    """
    msg                  = MIMEMultipart("alternative")
    msg["Subject"]       = lead.get("reply_subject") or f"Re: {lead.get('subject', 'Your Inquiry')}"
    msg["From"]          = f"{SENDER_NAME} <{SMTP_USER or 'demo@example.com'}>"
    msg["To"]            = lead["customer_email"]
    msg["Date"]          = datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")

    orig_mid = lead.get("original_message_id")
    if orig_mid:
        msg["In-Reply-To"] = orig_mid
        msg["References"]  = orig_mid

    # Use smart reply content if provided, otherwise fall back to generic template
    if lead.get("reply_body"):
        plain = lead["reply_body"]
        # Convert plain text to basic HTML for the HTML part
        html_body = re.sub(r'\n', '<br>', re.sub(r'&', '&amp;', plain))
        html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto">
      <div style="white-space:pre-wrap;line-height:1.6">{html_body}</div>
      <hr style="border:none;border-top:1px solid #eee;margin-top:2em">
      <p style="font-size:11px;color:#999">
        This email was sent by {SENDER_NAME}.
      </p>
    </body></html>"""
    else:
        plain = (
            f"Hi {lead.get('customer_name', 'there')},\n\n"
            f"Thank you for reaching out to us via {lead.get('channel', 'our platform')}.\n\n"
            f"We noticed we haven't had a chance to follow up with you yet - "
            f"we sincerely apologise for the delay!\n\n"
            f"We'd love to help you. Could we schedule a quick call or chat at your convenience? "
            f"Please reply to this email or reach us directly.\n\n"
            f"Warm regards,\n{SENDER_NAME}"
        )

        html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:auto">
      <p>Hi <strong>{lead.get('customer_name', 'there')}</strong>,</p>
      <p>Thank you for reaching out via <em>{lead.get('channel', 'our platform')}</em>.</p>
      <p>We noticed we haven't followed up - we sincerely apologise for the delay!</p>
      <p>We'd love to help. Could we schedule a quick call or chat at your convenience?
         Just reply to this email or reach us directly.</p>
      <p style="margin-top:2em">Warm regards,<br>
         <strong>{SENDER_NAME}</strong></p>
      <hr style="border:none;border-top:1px solid #eee;margin-top:2em">
      <p style="font-size:11px;color:#999">
        This email was sent by {SENDER_NAME}.
      </p>
    </body></html>"""

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html,  "html"))
    return msg


# ── SMTP send with retry ──────────────────────────────────────────────

def _smtp_send_with_retry(msg: MIMEMultipart, lead_id: str,
                          recipient: str,
                          customer_name: str = "") -> bool:
    """Send an email via SMTP with exponential-backoff retries.

    Returns True on success, False after all retries are exhausted.
    On permanent failure (bad credentials, invalid recipient) the retries
    stop early since retrying won't help.
    """
    last_error = None

    for attempt in range(1, SMTP_MAX_RETRIES + 1):
        try:
            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.sendmail(msg["From"], recipient, msg.as_string())
            # Success
            return True

        except smtplib.SMTPAuthenticationError as exc:
            # Auth failures are permanent — no point retrying
            last_error = exc
            print(f"[auto_followup] AUTH FAILED (no retry): {lead_id} — {exc}")
            break

        except smtplib.SMTPRecipientsRefused as exc:
            # Bad recipient — permanent, no retry
            last_error = exc
            print(f"[auto_followup] RECIPIENT REFUSED (no retry): {lead_id} — {exc}")
            break

        except (smtplib.SMTPException, ConnectionError, OSError, TimeoutError) as exc:
            # Transient errors — safe to retry
            last_error = exc
            if attempt < SMTP_MAX_RETRIES:
                delay = min(SMTP_RETRY_BASE * (2 ** (attempt - 1)), SMTP_RETRY_CAP)
                print(f"[auto_followup] RETRY {attempt}/{SMTP_MAX_RETRIES} "
                      f"in {delay:.0f}s — {lead_id}: {exc}")
                time.sleep(delay)
            else:
                print(f"[auto_followup] RETRY EXHAUSTED ({SMTP_MAX_RETRIES} attempts) "
                      f"— {lead_id}: {exc}")

        except Exception as exc:
            # Unexpected error — don't retry
            last_error = exc
            print(f"[auto_followup] UNEXPECTED ERROR (no retry): {lead_id} — {exc}")
            break

    # All retries failed — log to failed_leads.json
    failed = _load_failed()
    failed[lead_id] = {
        "customer_email": recipient,
        "customer_name":  customer_name,
        "subject":        msg["Subject"],
        "error":          str(last_error),
        "attempts":       SMTP_MAX_RETRIES,
        "failed_at":      datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
    }
    _save_failed(failed)
    return False


# ── Public API ────────────────────────────────────────────────────────

def send_followup(lead: dict, force: bool = False) -> bool:
    lead_id = lead.get("lead_id", "UNKNOWN")
    sent    = _load_sent()

    if lead_id in sent and not force:
        print(f"[auto_followup] SKIP  - {lead_id} already followed up.")
        return False

    msg = _build_email(lead)

    if DEMO_MODE:
        print(f"\n{'='*60}")
        print(f"[auto_followup] DEMO MODE - would send email:")
        print(f"  Lead ID  : {lead_id}")
        print(f"  To       : {lead['customer_email']}")
        print(f"  Subject  : {msg['Subject']}")
        print(f"  Channel  : {lead.get('channel')}")
        print(f"  Intent   : {lead.get('detected_intent', 'n/a')}")
        print(f"  Threaded : {'Yes' if lead.get('original_message_id') else 'No'}")
        print(f"{'='*60}\n")
    else:
        success = _smtp_send_with_retry(
            msg, lead_id, lead["customer_email"],
            customer_name=lead.get("customer_name", ""),
        )
        if not success:
            return False
        print(f"[auto_followup] SENT  - {lead_id} -> {lead['customer_email']}")

    sent.add(lead_id)
    _save_sent(sent)
    return True


def process_missed_leads(leads: list) -> dict:
    sent_count = skipped_count = failed_count = 0
    for lead in leads:
        ok = send_followup(lead)
        if ok:
            sent_count += 1
        else:
            # Distinguish skipped (already sent) from failed (retries exhausted)
            lead_id = lead.get("lead_id", "UNKNOWN")
            if lead_id in _load_sent():
                skipped_count += 1
            else:
                failed_count += 1
    print(f"\n[auto_followup] Batch done - Sent: {sent_count} | "
          f"Skipped: {skipped_count} | Failed: {failed_count}")
    return {"sent": sent_count, "skipped": skipped_count, "failed": failed_count}


if __name__ == "__main__":
    sample_leads = [
        {
            "lead_id"             : "L0042",
            "customer_email"      : "priya@example.com",
            "customer_name"       : "Priya",
            "channel"             : "WhatsApp",
            "subject"             : "Your Inquiry - Product Demo",
            "original_message_id" : "<abc123@mail.example.com>",
        },
        {
            "lead_id"             : "L0099",
            "customer_email"      : "ravi@example.com",
            "customer_name"       : "Ravi",
            "channel"             : "Email",
            "subject"             : "Your Inquiry - Pricing",
        },
    ]
    process_missed_leads(sample_leads)
    print("\n== Duplicate prevention test (same IDs again) ==")
    process_missed_leads(sample_leads)   # Both should print SKIP
